# Generated by Django 3.0 on 2023-07-09 23:37

from django.db import migrations, models
import django.db.models.deletion
import tallerMecanico.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(max_length=150)),
                ('fecha', models.DateField(null=True)),
                ('imagen', models.ImageField(upload_to='atenciones')),
                ('materiales', models.TextField(max_length=100)),
                ('publicado', models.BooleanField(default=False)),
                ('comentario', models.CharField(default='N/A', max_length=40)),
                ('trabajador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPostulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=40)),
                ('imagen', models.ImageField(upload_to='postulaciones')),
                ('cv', models.FileField(upload_to='postulaciones/cv', validators=[tallerMecanico.models.validate_pdf])),
                ('estado', models.CharField(choices=[('RECHAZADO', 'Rechazado'), ('ACEPTADO', 'Aceptado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('imagen_categoria', models.ImageField(upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_galeria', models.ImageField(null=True, upload_to='galeria')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.Atencion')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=40, null=True)),
                ('comentario', models.TextField(max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.TipoAtencion')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerMecanico.TipoAtencion'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mechanic', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', tallerMecanico.models.UserManager()),
            ],
        ),
    ]
